### ISSUE TITLE
Assertion !"unreachable" failed.

### ISSUE THREAD

**Issue by zyxwvuts** [nsf/termbox#50]
This was triggered by pasting more than 64 bytes to the terminal. I fixed this easily for my own purposes by increasing ENOUGH_DATA_FOR_PARSING, but I thought it would be worth noting.
Great job on the library, by the way, I love the design of it. :-)

**Comment by nsf** [comment]
That's a bug actually, I'll fix it.

**Comment by nsf** [comment]
Oh and if you like Go, or maybe haven't had a chance to check it out. Go's termbox version is the most featureful one: https://github.com/nsf/termbox-go

Just a silly suggestion to check it out. I like Go mostly because it provides built-in primitives for dealing with event loops, while C version ideally should be embeddable into various main loop libraries (such as GMainLoop or libev or you name it).

**Comment by nsf** [comment]
Should be fixed by a pull request: https://github.com/nsf/termbox/pull/52

**Comment by zyxwvuts** [comment]
I've tested it in the same use-case with pastes of various lengths (up to 32768 bytes) and I had no issues with this new commit.
